stages:
  build:
    nodeLabel: nvm-sbt
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        set -x
        sbt test
    filesToStash:
      - '**'
  deployProd:
    nodeLabel: nvm-sbt-deployer
    secrets:
      CLOUDFLARE_AUTH_KEY: scheduled-maintenance/cloudflare-api-key
      CLOUDFLARE_AUTH_EMAIL: scheduled-maintenance/cloudflare-email-address
      CLOUDFLARE_ACCOUNT_ID: scheduled-maintenance/cloudflare-account
      CLOUDFLARE_ZONE_ID: scheduled-maintenance/cloudflare-zone
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        set -x
        npm install -g serverless serverless-cloudflare-workers
        export CLOUDFLARE_WORKER_ROUTE='api-sandbox.dwolla.com'
        sbt deploy
additionalJobs:
  - name: End Scheduled Maintenance
    nodeLabel: nvm-deployer
    checkout: true
    secrets:
      CLOUDFLARE_AUTH_KEY: scheduled-maintenance/cloudflare-api-key
      CLOUDFLARE_AUTH_EMAIL: scheduled-maintenance/cloudflare-email-address
      CLOUDFLARE_ACCOUNT_ID: scheduled-maintenance/cloudflare-account
      CLOUDFLARE_ZONE_ID: scheduled-maintenance/cloudflare-zone
    steps:
      - |
        set +x
        . ${NVM_DIR}/nvm.sh --no-use
        nvm install
        set -x
        npm install -g serverless serverless-cloudflare-workers
        serverless remove
